id: A03B98249
title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
type: translation
pechas:
- I56B67F6B
- ID0DACDDE
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:01:34.983503
  last_modified_at: 2023-01-04 12:01:34.983517
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I56B67F6B/A8DE: 7E87
  ID0DACDDE/236C: 7E87
